### PR TITLE
docs(readme): fill 'contact' section

### PR DESCRIPTION
**Pull request by Charlotteis**
This is how you can contact Jan & I on the internets should the need arise.
Am not currently able to receive emails to my new account, but I can send emails from it. Hopefully the receiving will come soon!

### CODE REVIEW

**Comment by Charlotteis** [comment]
Closes #18

**Comment by Charlotteis** [comment]
Update: I can send emails to my charlotte@hood.ie account, most of the time.

**Comment by bnb** [comment]
Can this be merged and closed? If so, https://github.com/hoodiehq/editorial/issues/18 should be closed.

**Comment by Charlotteis** [comment]
I merged it. It's not a process change and one LGTM is good enough for me. Thanks!

**Pull request merged**
