### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Charlotteis**
Added a link to the code of conduct

I removed words like "we need a superb... we need an excellent" because you do not need to be superb nor excellent people. We need nice people who write nice words and we can work with them to make great posts. It's kind of like when someone tells me I need to be "super passionate" about my job all the time to get hired and I'm like "well sometimes I'm tired and bored, actually".

Hope this helps.

### CODE REVIEW

**Comment by Charlotteis** [comment]
Will later add a PR to add a paragraph on contacting some of us privately, but I need to see if I can get a separate email for this first.

**Comment by Charlotteis** [comment]
Great points @bnb. I updated some of the text, hope it reads better now.

**Comment by bnb** [comment]
LGTM. :shipit:

**Comment by remixz** [comment]
Heh, I just added those words because I wanted to add some dorky alliteration. :laughing: Totally fine with removing them. :+1:

**Comment by bnb** [comment]
Can this be merged?

**Comment by Charlotteis** [comment]
@bnb was just coming here to do this. Thank you :)

**Pull request merged**
