### PR TITLE
review-meet-the-hoodies-charlotteis

### PR DESCRIPTION
**Pull request by schisepo**
Hi @everyone

Please review this blog post :smiley:

### CODE REVIEW

**Comment by Charlotteis** [comment]
Could you also add my Twitter? Just because thats the best way to get in touch with me :)

[Twitter - @Charlotteis](https://github.com/charlotteis)
Also I think we need to download the fox and thumbsup images and host them ourselves (putting them in the dist folder) so we don't hotlink to other websites?

**Comment by schisepo** [comment]
Noted. Will do 😊

**Comment by Charlotteis** [comment]
I'm not sure those waffle commits should be on this branch?

**Comment by Charlotteis** [comment]
Also we still need to add the images separately, but I guess someone can do that when the PR to the main website?

**Comment by Charlotteis** [comment]
Would someone like to open a PR on the main website, preparing this post for publishing? Making sure to grab local copies of the images i linked to, compressing them, and putting them into the Hood.ie dist folders.

**Comment by schisepo** [comment]
@charlotteis - You're right about the waffle.io commits. I should have done them on a separate branch. Let me see whether I can correct this. If no one's come forward to try the PR to hoodiehq in a couple of hours, I'll do this one as well.

**Comment by espy** [comment]
I'm on it!

**Comment by espy** [comment]
There you go! https://github.com/hoodiehq/hood.ie/pull/221

**Comment by Charlotteis** [comment]
thank you @espy <3 <3 <3

**Comment by Charlotteis** [comment]
Gonna go ahead and merge this, as the post already went out.
Happy to leave the waffle commits in.

**Pull request merged**
