### PR TITLE
Add issue body to link

### PR DESCRIPTION
**Pull request by gr2m**
- I copied the <code>\`\`\`md ... \`\`\`</code> part
- pased it here http://meyerweb.com/eric/tools/dencoder/, cliked the `encode` button
- copied the output, and added it to the new issue url as `&body=<otuput here>`

### CODE REVIEW

**Comment by bnb** [comment]
Since it looks like you're just filling the new issue for them by default, it shouldn't tell them to paste it into the new issue. This is telling them to do something and then doing it for them. I would do something like `[click this link to open a new issue with this format]() or [paste it in yourself]()`. Up to your discretion, but I think it needs to be slightly altered to not be confusing.

**Comment by gr2m** [comment]
better? https://github.com/hoodiehq/editorial/blob/gr2m-patch-1/documents/pitch-template.md

**Comment by bnb** [comment]
How about `[Automatically create a pitch issue](), or copy and paste the form below into a [new issue]()`? Again, up to you, but the updated one is still a bit confusing to me.

**Comment by gr2m** [comment]
updated: https://github.com/hoodiehq/editorial/blob/gr2m-patch-1/documents/pitch-template.md

**Comment by bnb** [comment]
+1 :shipit:

**Comment by Charlotteis** [comment]
Wow nice one, thanks!

**Pull request merged**
