### PR TITLE
Added CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by bnb**
Added first draft of CONTRIBUTORS.md. Nit and edit away!

### CODE REVIEW

**Comment by schisepo** [comment]
:+1: LGTM (Borrowed :smile: )

**Comment by renrutnnej** [comment]
Are we listing all of the editorial contributors in an md?

My understanding of the issue (https://github.com/hoodiehq/editorial/issues/18) was to identify some core Hoodie contributors to contact with questions, which I think should be identified in the README. 

I think both could be useful btw ☺️ I just want to be clear on the initial purpose the issue was getting at.

**Comment by Charlotteis** [comment]
I think this is not for #18, but can be merged as it is good work.
@janl  and I need to work on #18 but am waiting on dedicated email creation first then I can add details to the README.

Before this is merged, it looks like there might be some extra spaces in the "Why would I want to be one?" title. I know @bnb is busy with their final term though so someone else can fix that on this PR?

**Comment by Charlotteis** [comment]
@bnb just a little edited I asked for above, to do with extra spaces left in, and I am happy to merge this :star2:

**Comment by janl** [comment]
merged & fixed whitespace in a second commit as it was easier for me, hope that was cool

**Comment by Charlotteis** [comment]
Thanks :)

**Pull request merged**
