### PR TITLE
feat: add @renrutnnej's meet-the-hoodie interview

### PR DESCRIPTION
**Pull request by Charlotteis**
I had to remove an emoji as it won't render on the hood.ie website. Also added a couple of line breaks.
@renrutnnej please could you let me know if I've not rendered this faithfully from your Hackpad.

Everyone else, please review this!
And if someone could volunteer for PR'ing it to the Hoodie website once we're happy with it!

### CODE REVIEW

**Comment by Charlotteis** [comment]
LGTM :)

> I can identify several periods of my life by when I had to “burn” and start again. 

Is such a strong sentence that I identify with. I'll remember it forever.

**Comment by janl** [comment]
LGTM! :)

If nobody objects, I’ll post this tomorrow 11-ish CET.

**Comment by schisepo** [comment]
Great writing @renrutnnej 😃 Looks good to me too.

**Comment by renrutnnej** [comment]
Woo hoo, thanks everyone!

**Comment by Charlotteis** [comment]
Thank you so much for picking up where I left off @janl. My todo list... it's making me cry.

**Comment by janl** [comment]
I’ll be merging this, but I want to propose a change to the process: I have to manually add this to the hood.ie repo now, and then we have the same blog post in two repos. I don’t think that’s useful for anyone. Could we, in the future, send blog post PRs directly against the github.com/hoodiheq/hood.ie repo?

**Comment by janl** [comment]
We are live http://hood.ie/blog/meet-the-hoodies-jenn-turner.html

**Comment by janl** [comment]
We are live: http://hood.ie/blog/meet-the-hoodies-jenn-turner.html

**Pull request merged**
