### PR TITLE
fix(team-roles): remove use of 'simple'

### PR DESCRIPTION
**Pull request by Charlotteis**
Remove the use of 'simple' from the copy-editing role. Nothing is ever simple!

(Good work on the team-roles, @remixz :))

### CODE REVIEW

**Comment by bnb** [comment]
LGTM. :shipit:

**Comment by remixz** [comment]
:+1:

**Comment by bnb** [comment]
Merge conflicts as of https://github.com/hoodiehq/editorial/pull/23, solution at https://github.com/hoodiehq/editorial/pull/27.

**Comment by Charlotteis** [comment]
Was done by @bnb at #27. Thanks.

**Pull request closed without merging**
